version: '3'

services:
  kafka-cluster:
    image: lensesio/fast-data-dev:2.2
    environment:
      ADV_HOST: 127.0.0.1
      RUNTESTS: 0           #Disable running tests so the cluster starts faster
      FORWARDLOGS: 0        #No log forwarding to kafka topics
      SAMPLEDATA: 0         #No sample data
    ports:
    - 2181:2181             #ZooKeeper
    - 3030:3030             #Lenses UI
    - 8081-8083:8081-8083   #REST proxy, schema registry, kafka connect
    - 9581-9585:9581-9585   #JMX
    - 9092:9092             #Kafka Broker